modLoader="javafml"
loaderVersion="[1,)"
license="${mod_license}"
issueTrackerURL="${issue_url}"
showAsResourcePack=false

[[mods]]
modId="template"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
#credits=""
description='''${mod_description}'''
logoFile="assets/${mod_id}.png"
displayURL="${homepage_url}"
#updateJSONURL=""
#displayTest="MATCH_VERSION" # MATCH_VERSION/IGNORE_SERVER_VERSION/IGNORE_ALL_VERSION/NONE

[[mixins]]
config="template.mixins.json"
[[mixins]]
config="template-neoforge.mixins.json"

[[dependencies.template]]
modId = "minecraft"
mandatory = true
versionRange = "${mc_range}"
ordering = "NONE" # BEFORE/AFTER/NONE
side = "BOTH" # CLIENT/SERVER/BOTH

[[dependencies.template]]
modId = "neoforge"
mandatory = true
versionRange = "${neo_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.template]]
modId = "architectury"
mandatory = true
versionRange = "[${arch_version},)"
ordering = "AFTER"
side = "BOTH"

#[[dependencies.template]]
#modId="terrablender"
#mandatory=true
#versionRange="[${tb_version},)"
#ordering="NONE"
#side="BOTH"